version: '3'

networks:
  psql:
    name: network_name

services:
  nginx:
    build: .
    networks:
      - network_name
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs:/etc/nginx/conf.d"
      - "./letsencrypt:/etc/letsencrypt"
